package view;

import static application.MainApp.ListaOrdensServicos;
import static application.MainApp.clienteAtivo;
import static application.MainApp.ordemServicoAtiva;
import static application.MainApp.ordemServicoController;
import static application.MainApp.propriedadeController;
import static application.MainApp.veiculoController;
import static application.MainApp.veiculoAtivo;
import static application.MainApp.clienteController;
import static application.MainApp.funcionarioController;
import static application.MainApp.propriedadeAtiva;
import utils.Utils;
import utils.Utils.DialogBoxes;
import static utils.Utils.DialogBoxes.convertStringToDateTime;
import static utils.Utils.DialogBoxes.getCurrentDateTime;
import model.Cliente;
import model.Funcionario;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.OrdemServico;
import model.Propriedade;
import model.Veiculo;
import controller.enums.StatusOS;
import static controller.enums.StatusOS.ABERTA;
import controller.enums.StatusPagamento;
import static controller.enums.StatusPagamento.ABERTO;
import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author leoni
 */
public class frmOrdemServicoLista extends javax.swing.JFrame {

    /**
     * Creates new form frm
     */
    public frmOrdemServicoLista() {
        initComponents();        
        this.setLocationRelativeTo(null);        
        this.setResizable(false);        
        carregarOrdemServicos();        
    }

    public void carregarOrdemServicos() {
        
        
        boolean blnZero = false;

        // Lista as ordens de serviço ativas
        ListaOrdensServicos = ordemServicoAtiva.listarOrdemServico();

        // Verifica se a lista de ordens de serviço não está vazia
        if (!ListaOrdensServicos.isEmpty()) {
            blnZero = true;
        } else {
            System.out.println("Nenhuma linha selecionada.");
        }

        int selectedRow = jTable1.getSelectedRow();

        // Obtemos o modelo da tabela
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);  // Limpa as linhas da tabela

        // Adiciona os dados de cada ordemServico na tabela        
        for (OrdemServico ordemServico : ListaOrdensServicos) {
            try {
                // Verifique se ordemServico não é nulo
                if (ordemServico == null) {
                    System.out.println("ordemServico é nulo.");
                    continue;
                }
                
                // Cria a linha de dados para a tabela
                String[] coluna = new String[6]; // Corrigido para tamanho 6
                coluna[0] = String.valueOf(ordemServico.getId());
                coluna[1] = String.valueOf(ordemServico.getValorFinal());
                coluna[2] = ordemServico.getPlaca();
                coluna[3] = String.valueOf(ordemServico.getData());
                coluna[4] = (ordemServico.getStatus() != null) ? ordemServico.getStatus().toString() : "N/A";
                coluna[5] = ""; // Adicione uma sexta coluna vazia, se necessário

                // Adiciona a linha com os dados à tabela
                model.addRow(coluna);

            } catch (Exception e) {
                e.printStackTrace(); // Imprime a pilha de erros para ajudar na depuração
                JOptionPane.showMessageDialog(null,
                        "Erro ao adicionar ordem de serviço na tabela:\n" + e.getMessage(),
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }

        // Verifica se o índice está dentro dos limites da tabela
        if (selectedRow >= 0 && selectedRow < jTable1.getRowCount()) {
            // Seleciona a linha especificada
            jTable1.setRowSelectionInterval(selectedRow, selectedRow);

            // Opcional: Desloca a tabela para a linha selecionada
            jTable1.scrollRectToVisible(jTable1.getCellRect(selectedRow, 0, true));
        } else {
            System.out.println("Índice da linha fora dos limites.");
        }

        // Atualiza o estado dos botões
        jButton2.setEnabled(blnZero);
        jButton3.setEnabled(blnZero);
        jButton4.setEnabled(blnZero);
}

            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CarSys - Administrativo");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Ordem de Servico");

        jLabel2.setText("Adicione novos, altere ou consulte informacoes sobre os ja cadastrados.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(489, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Valor", "Placa do Veiculo", "Iniciada Em", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTable1MouseMoved(evt);
            }
        });
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jTable1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Novo...");
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edita...");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remove...");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Atualizar");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Fechar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Pecas...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Servicos...");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Pagamentos...");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton7)
                        .addComponent(jButton8))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4)
                        .addComponent(jButton5)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OS.jpg"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // Obtém o próximo ID de ordem de serviço
        int idOrdemServico = ordemServicoController.proximaOrdemServico();

        // Solicitar a placa do veículo
        String placaVeiculo = JOptionPane.showInputDialog(null,"Entre com a placa do Veículo:");

        // Verifica se existe uma OS aberta para a placa informada
        OrdemServico osExistente = ordemServicoController.buscarOrdemServicoAbertaPorPlaca(placaVeiculo);

        if (osExistente != null) {
            int resposta = JOptionPane.showConfirmDialog(null,
                    "Já existe uma ordem de serviço aberta para esta placa: " + osExistente.getPlaca() + "\nVocê deseja iniciar uma nova ordem de serviço?",
                    "Confirmação de Ação",
                    JOptionPane.YES_NO_OPTION);

            if (resposta != JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(null, "Ação cancelada. Não é possível abrir uma nova ordem de serviço enquanto houver uma aberta.");
                return;
            }
        }

// Solicitar dados do cliente e funcionário
        String idCliente = JOptionPane.showInputDialog(null,"Entre com o ID do Cliente:");
        String cpfFuncionario = JOptionPane.showInputDialog(null,"Entre com o CPF do Funcionário:");

// Verificar se os dados são válidos
        Cliente cliente = clienteController.buscarCliente(Integer.valueOf(idCliente));
        Veiculo veiculo = veiculoController.buscarVeiculoPorPlaca(placaVeiculo);
        Funcionario funcionario = funcionarioController.buscarFuncionario(cpfFuncionario);

        if (cliente != null && veiculo != null && funcionario != null) {
            OrdemServico ordemServicoAtivaP = new OrdemServico(
                    idOrdemServico, // ID
                    convertStringToDateTime(getCurrentDateTime()), // Data
                    veiculo.getPlacaPK(), // Placa do veículo
                    BigDecimal.ZERO, // Valor Final
                    BigDecimal.ZERO, // Valor Pago
                    StatusOS.ABERTA, // Status da OS
                    cliente,
                    veiculo,
                    funcionario
            );
            application.MainApp.ordemServicoAtiva = ordemServicoAtivaP;
            ordemServicoController.criarOrdemServico(ordemServicoAtivaP);            

            carregarOrdemServicos();
        } else {
            JOptionPane.showMessageDialog(null, "Cliente, Veículo ou Funcionário não encontrados.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        frmOrdemServicoFind pesquisa = new frmOrdemServicoFind(this, true);
        pesquisa.setLocationRelativeTo(this);
        pesquisa.setVisible(true);
        // Abre a janela de edição de ordemServicos
        if (ordemServicoAtiva.getPlaca()!=""){        
            frmOrdemServicoEdita cadastroClients = new frmOrdemServicoEdita(this, true);
            cadastroClients.setLocationRelativeTo(this);
            cadastroClients.setVisible(true);
        }       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    // Solicita o código do ordemServico a ser removido
String idOrdemServico = JOptionPane.showInputDialog("Entre com o código do ordemServico a ser removido:");
if (idOrdemServico != null && !idOrdemServico.isEmpty()) {
            try {
                Integer codOrdemServico = Integer.parseInt(idOrdemServico);

                // Busca o ordemServico pelo código fornecido
                OrdemServico ordemServico = ordemServicoController.buscarOrdemServico(codOrdemServico);

                if (ordemServico != null) {
                    int resposta = JOptionPane.showConfirmDialog(null,
                            "OrdemServico a ser removido: " + ordemServico.getPlaca() + "\nVocê tem certeza que deseja remover este ordemServico?",
                            "Confirmação de Remoção",
                            JOptionPane.YES_NO_OPTION);

                    if (resposta == JOptionPane.YES_OPTION) {
                        ordemServicoController.deletarOrdemServico(codOrdemServico);
                        JOptionPane.showMessageDialog(null, "OrdemServico removido com sucesso.");
                        ordemServicoController.listarOrdemServico();
                        carregarOrdemServicos();
                    } else {
                        JOptionPane.showMessageDialog(null, "A remoção do ordemServico não foi confirmada.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "OrdemServico não encontrado ou nome completo não disponível.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Código do ordemServico inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Código do ordemServico não pode ser vazio.", "Erro", JOptionPane.ERROR_MESSAGE);
        }



    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            
        carregarOrdemServicos(); 
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
        
    }//GEN-LAST:event_jButton1FocusGained

    private void jTable1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1CaretPositionChanged
      
    }//GEN-LAST:event_jTable1CaretPositionChanged

    private void jTable1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseMoved

    }//GEN-LAST:event_jTable1MouseMoved

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        try {
            int selectedRow = jTable1.getSelectedRow(); // A linha selecionada

            if (selectedRow != -1) { // Verifica se uma linha foi selecionada
                try {
                    // Pega o valor da célula da primeira coluna
                    Object value = jTable1.getValueAt(selectedRow, 0);
                    Integer idOrdemServicoAtivo = null;

                    // Verifica o tipo do valor da célula e realiza a conversão adequada
                    if (value instanceof String) {
                        idOrdemServicoAtivo = Integer.valueOf((String) value);
                    } else if (value instanceof Integer) {
                        idOrdemServicoAtivo = (Integer) value;
                    }

                    if (idOrdemServicoAtivo != null) {
                        // Realiza a busca pelo ordemServico ativo
                        ordemServicoAtiva = ordemServicoController.buscarOrdemServico(idOrdemServicoAtivo);
                        // Exibe o valor do ID do ordemServico
                        System.out.println("ID OrdemServico Ativo: " + idOrdemServicoAtivo);

                        // Abre a janela de edição de ordemServicos
                        frmOrdemServicoEdita cadastroOrdemServico = new frmOrdemServicoEdita(this, true);
                        cadastroOrdemServico.setLocationRelativeTo(this);
                        cadastroOrdemServico.setVisible(true);

                    } else {
                        System.out.println("Valor do ID do ordemServico é nulo.");
                    }
                } catch (NumberFormatException e) {
                    // Trata a exceção caso o valor não seja um número válido
                    System.out.println("Formato de número inválido: " + e.getMessage());
                    e.printStackTrace();
                } catch (ClassCastException e) {
                    // Trata a exceção caso o valor não seja do tipo esperado
                    System.out.println("Valor do ID do ordemServico inválido: " + e.getMessage());
                    e.printStackTrace();
                } catch (Exception e) {
                    // Trata possíveis exceções ao buscar ordemServico e abrir a janela
                    System.out.println("Erro ao buscar ordemServico ou abrir a janela: " + e.getMessage());
                    e.printStackTrace();
                }
            } else {
                // Caso não haja nenhuma linha selecionada
                System.out.println("Nenhuma linha selecionada.");
            }
            carregarOrdemServicos();            
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        carregarOrdemServicos();
    }//GEN-LAST:event_jTable1FocusGained

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        int selectedRow = jTable1.getSelectedRow(); // A linha selecionada

        if (selectedRow != -1) { // Verifica se uma linha foi selecionada
            try {
                // Pega o valor da célula da primeira coluna
                Object value = jTable1.getValueAt(selectedRow, 0);
                Integer idOrdemServicoAtivo = null;

                // Verifica o tipo do valor da célula e realiza a conversão adequada
                if (value instanceof String) {
                    idOrdemServicoAtivo = Integer.valueOf((String) value);
                } else if (value instanceof Integer) {
                    idOrdemServicoAtivo = (Integer) value;
                }

                if (idOrdemServicoAtivo != null) {
                    // Realiza a busca pelo ordemServico ativo
                    ordemServicoAtiva = ordemServicoController.buscarOrdemServico(idOrdemServicoAtivo);
                    // Exibe o valor do ID do ordemServico
                    System.out.println("ID OrdemServico Ativo: " + idOrdemServicoAtivo);

                    // Abre a janela de edição de ordemServicos
                    frmOrdemServicoEditarItensPecas cadastroOrdemServico = new frmOrdemServicoEditarItensPecas();
                    cadastroOrdemServico.setLocationRelativeTo(this);
                    cadastroOrdemServico.setVisible(true);
                    
                } else {
                    System.out.println("Valor do ID do ordemServico é nulo.");
                }
            } catch (NumberFormatException e) {
                // Trata a exceção caso o valor não seja um número válido
                System.out.println("Formato de número inválido: " + e.getMessage());
                e.printStackTrace();
            } catch (ClassCastException e) {
                // Trata a exceção caso o valor não seja do tipo esperado
                System.out.println("Valor do ID do ordemServico inválido: " + e.getMessage());
                e.printStackTrace();
            } catch (Exception e) {
                // Trata possíveis exceções ao buscar ordemServico e abrir a janela
                System.out.println("Erro ao buscar ordemServico ou abrir a janela: " + e.getMessage());
                e.printStackTrace();
            }
        } else {
            // Caso não haja nenhuma linha selecionada
            System.out.println("Nenhuma linha selecionada.");
        }                        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        int selectedRow = jTable1.getSelectedRow(); // A linha selecionada

        if (selectedRow != -1) { // Verifica se uma linha foi selecionada
            try {
                // Pega o valor da célula da primeira coluna
                Object value = jTable1.getValueAt(selectedRow, 0);
                Integer idOrdemServicoAtivo = null;

                // Verifica o tipo do valor da célula e realiza a conversão adequada
                if (value instanceof String) {
                    idOrdemServicoAtivo = Integer.valueOf((String) value);
                } else if (value instanceof Integer) {
                    idOrdemServicoAtivo = (Integer) value;
                }

                if (idOrdemServicoAtivo != null) {
                    // Realiza a busca pelo ordemServico ativo
                    ordemServicoAtiva = ordemServicoController.buscarOrdemServico(idOrdemServicoAtivo);
                    // Exibe o valor do ID do ordemServico
                    System.out.println("ID OrdemServico Ativo: " + idOrdemServicoAtivo);

                    // Abre a janela de edição de ordemServicos
                    frmOrdemServicoEditarItensServicos cadastroOrdemServico = new frmOrdemServicoEditarItensServicos();
                    cadastroOrdemServico.setLocationRelativeTo(this);
                    cadastroOrdemServico.setVisible(true);
                    
                } else {
                    System.out.println("Valor do ID do ordemServico é nulo.");
                }
            } catch (NumberFormatException e) {
                // Trata a exceção caso o valor não seja um número válido
                System.out.println("Formato de número inválido: " + e.getMessage());
                e.printStackTrace();
            } catch (ClassCastException e) {
                // Trata a exceção caso o valor não seja do tipo esperado
                System.out.println("Valor do ID do ordemServico inválido: " + e.getMessage());
                e.printStackTrace();
            } catch (Exception e) {
                // Trata possíveis exceções ao buscar ordemServico e abrir a janela
                System.out.println("Erro ao buscar ordemServico ou abrir a janela: " + e.getMessage());
                e.printStackTrace();
            }
        } else {
            // Caso não haja nenhuma linha selecionada
            System.out.println("Nenhuma linha selecionada.");
        } 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
        int selectedRow = jTable1.getSelectedRow(); // A linha selecionada

        if (selectedRow != -1) { // Verifica se uma linha foi selecionada
            try {
                // Pega o valor da célula da primeira coluna
                Object value = jTable1.getValueAt(selectedRow, 0);
                Integer idOrdemServicoAtivo = null;

                // Verifica o tipo do valor da célula e realiza a conversão adequada
                if (value instanceof String) {
                    idOrdemServicoAtivo = Integer.valueOf((String) value);
                } else if (value instanceof Integer) {
                    idOrdemServicoAtivo = (Integer) value;
                }

                if (idOrdemServicoAtivo != null) {
                    // Realiza a busca pelo ordemServico ativo
                    ordemServicoAtiva = ordemServicoController.buscarOrdemServico(idOrdemServicoAtivo);
                    // Exibe o valor do ID do ordemServico
                    System.out.println("ID OrdemServico Ativo: " + idOrdemServicoAtivo);

                    // Abre a janela de edição de ordemServicos
                    frmOrdemServicoEditarItensPagamentos cadastroOrdemServico = new frmOrdemServicoEditarItensPagamentos();
                    cadastroOrdemServico.setLocationRelativeTo(this);
                    cadastroOrdemServico.setVisible(true);
                    
                } else {
                    System.out.println("Valor do ID do ordemServico é nulo.");
                }
            } catch (NumberFormatException e) {
                // Trata a exceção caso o valor não seja um número válido
                System.out.println("Formato de número inválido: " + e.getMessage());
                e.printStackTrace();
            } catch (ClassCastException e) {
                // Trata a exceção caso o valor não seja do tipo esperado
                System.out.println("Valor do ID do ordemServico inválido: " + e.getMessage());
                e.printStackTrace();
            } catch (Exception e) {
                // Trata possíveis exceções ao buscar ordemServico e abrir a janela
                System.out.println("Erro ao buscar ordemServico ou abrir a janela: " + e.getMessage());
                e.printStackTrace();
            }
        } else {
            // Caso não haja nenhuma linha selecionada
            System.out.println("Nenhuma linha selecionada.");
        }   
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOrdemServicoLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOrdemServicoLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOrdemServicoLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOrdemServicoLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOrdemServicoLista().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
